services:
  db:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - foodieee-network
networks:
  foodieee-network:
    driver: bridge
volumes:
  pgdata:
    driver: local
